### ISSUE TITLE
Unify types and Methods

### ISSUE THREAD

**Issue by blaggacao** [skilld-labs/go-odoo#13]
I think this whole structure is pretty confusing, why not define the types in the same file as the API is defined?? Not sure, but I thought go is pretty srict on how the folder layout should be and where the files should go, and how repos should be organized, and I have the feeling this is not how it should be done...

See: https://github.com/rancher/go-rancher/blob/master/v2/generated_client.go

Btw: if I run dep init it will not recognize the repo and when I run it within the api folder it get's even stranger...

**Comment by blaggacao** [comment]
trying to address this: https://github.com/xoes/go-odoo

**Comment by ahuret** [comment]
API has been reworked, I think the code is pretty clear now :)  Closing it.
