### ISSUE TITLE
Seeding Interface Discussion

### ISSUE THREAD

**Issue by blaggacao** [skilld-labs/go-odoo#19]
Big question going forward for https://github.com/xoe-labs/odoo-operator:

- What should be the best instance seeding interface?

Options:

- SQL templates (advantage: use standard `sql` golang libraries)
- CSV templates (disadvantage: need a wrapper around `def load`)
- A full OdooEnv CLI in golang (disadvantage: code needed. advantage: poke around more easily through golang scripts)

But really is there anything that cannot be done through a well crafted SQL template?

#Disintermediation

Note: I post it here as you guys have built the most comprehensive golang Odoo interface...

**Comment by blaggacao** [comment]
@jbguerraz Whatever comes out of this, I'd like to PR the outcome to this library.

**Comment by guewen** [comment]
> But really is there anything that cannot be done through a well crafted SQL template?

Triggering recomputation of computed/related/parent fields?

**Comment by blaggacao** [comment]
> Triggering recomputation of computed/related/parent fields?

This would be basically mean all the Compact-Partner computed ones...

**Comment by blaggacao** [comment]
I think the best thing to do is **not** abstracting Odoo's internal API but rather morphing it into a CLI tool. Therefore: https://github.com/acsone/click-odoo-contrib/issues/11
