### ISSUE TITLE
Fetching recurring event gives an error due to missmatching event's ID type

### ISSUE THREAD

**Issue by Gumaa** [skilld-labs/go-odoo#21]
When fetching recurring `calendar.event` instead of event's ID beeing integer we get ID as a string. 
Something like this :
`'id': '10842-20190730060000'`

And because of it we get an error during run time:
`http: panic serving [::1]:58720: reflect.Set: value of type string is not assignable to type int64`

**Solution:**
Change `Id` type inside `go-odoo > types` from `int64` to `interface{}` like this:
```go
Id                       interface{} `xmlrpc:"id"`
```

Didn't check updating or deleting such records yet. But I guess it would not work as this methods still use `int64`.

**Comment by ahuret** [comment]
And why not `string` instead of `interface{}`

**Comment by Gumaa** [comment]
Because the `Id` sometimes is still just an `Int`.
It would also break existing code:
`reflect.Set: value of type int64 is not assignable to type string`

So the `interface{}` is the easiest solution - but not perfect and there is still work to be done with create, update etc...

**Comment by ahuret** [comment]
Hey @Gumaa. All go-odoo api has changed. Please check if issue still exists with new version. thx.

**Comment by ahuret** [comment]
Closing it. Reopen it if you still get the issue.
