### ISSUE TITLE
How I can use args with ExecuteKw

### ISSUE THREAD

**Issue by m-abdalrahman** [skilld-labs/go-odoo#27]
I'm trying to attach a file with [message_post](https://www.odoo.com/documentation/13.0/reference/mixins.html#basic-messaging-system) using [ExecuteKw](https://pkg.go.dev/github.com/skilld-labs/go-odoo#Client.ExecuteKw), but I don't know how to add the id to attachment_ids

` c.ExecuteKw("message_post", AccountInvoiceModle, []interface{}{inv.ID, ?}, nil)`

**Comment by ahuret** [comment]
according to the doc you could try something like 
```go
c.ExecuteKw("method_post", AccountInvoiceModle, []interface{
	"here the body !",
	"here the message type",
	parent_id,
	[]interface{}{
		map[string]string{"attachmentname1": "attachmentcontent1"}, 
		map[string]string{"attachmentname2": "attachmentcontent2"},
	},
}, options)
```
Tell me if that help !

Btw you could contribute to go-odoo by adding high level method MessagePost, would be cool ! I can help you with that too ! 
Let me know :-)

**Comment by ahuret** [comment]
I'm closing this. Please reopen if you have issues related to this thread.
