### ISSUE TITLE
How to pass keywords to ExecuteKw() ?

### ISSUE THREAD

**Issue by bhuisgen** [skilld-labs/go-odoo#36]
Hello,

For a specific action I need to pass keywords to ExecuteKw(). Is this case possible with the current code ? The XML RPC client seems to not support that or am I wrong ? If you have any advice to achieve this part, I would be thankful.

**Comment by ahuret** [comment]
hey @bhuisgen sorry for such long delay, I slipped my mind :/
I've been able to do such thing like this :
```
client.ExecuteKw("action_invoice_open", "account.invoice", []interface{}{ids}, nil)
```
for example here, it "validates" an invoice for all invoice `ids`  mentionned. Does it answer your question ?

**Comment by ahuret** [comment]
closing it for now, feel free to ask if you have any question !
