### ISSUE TITLE
Is it possible to do full text search with the library?

### ISSUE THREAD

**Issue by jsebasmuller** [skilld-labs/go-odoo#44]
Hello it's me again xd, I would like to know if it is possible to do a search for all the fields that match the word I want to search for. Thanks for the answers

**Comment by ahuret** [comment]
what do you mean, you want to search for all the records from a model that match a specific word ?

**Comment by jsebasmuller** [comment]
I don't know if you have heard the concept of full text search, I have used it in mongo, which consists of creating an index and it searches the specified text in any field of the model.

**Comment by ahuret** [comment]
As I know there's not such feature in odoo. Closing it for now, please reopen or add comments if you found a way.
