### ISSUE TITLE
omptempty instead of omitempty

### ISSUE THREAD

**Issue by dragonis41** [skilld-labs/go-odoo#53]
Hi, 

In all structs, there is a typo in the xmlrpc field, the tag `omptempty` does not exist

**Comment by dragonis41** [comment]
Just saw the commit 780bce5 where all fix are reverted to omptempty, why ?
The xmlrpc you are using is clear :
> for fields tagged with ",omitempty", empty values are omitted;
And in the code there is no support for `omptempty`

**Comment by ahuret** [comment]
very weird, indeed, I don't remember at all why it has been done this way.
Thanks for reporting! I would be open for a pull request to fix it, note that the generator template has to be modified too https://github.com/skilld-labs/go-odoo/blob/master/generator/cmd/tmpl/model.tmpl#L5

**Comment by dragonis41** [comment]
I can do a PR yes, it won't take long to fix ^^

**Comment by dragonis41** [comment]
Here you go !
